### PR TITLE
add roadrunner2/macbook12-spi-driver

### PR DESCRIPTION
**Pull request by arno01**
Have tested this on my ``MacBookPro14,3`` (mid-2017), everything worked like a charm.

What's not working (neither with the Linux upstream applespi drivers in linux-5.3, linux-5.4) are some key combinations, such as:

- Ctrl+Alt+F1..12 in X11, console probably as well.. but Alt+Left/Right is a wokaround;
- Ctrl-X, F10 keys in Grub2, this is a known issue: [read 1](https://github.com/Dunedan/mbp-2016-linux/issues/54#issuecomment-370217326), [read 2](https://lists.gnu.org/archive/html/grub-devel/2017-03/msg00012.html) ; This forces me to write ``multiboot2 .., module2 ..., module2 ..., boot`` manually in order to add ``module_blacklist=xen_pciback`` parameter to the end of ``/vmlinuz`` so the system won't freeze during ``qubes-vm@sys-net`` installation/start-up, and only then I can ``qvm-pci detach sys-net dom0:03_00.0`` (where ``03:00.0`` is the ``Broadcom Limited BCM43602 802.11ac Wireless LAN SoC (rev 02)`` wifi adapter); Probably there could be a better way around using ``qubesctl`` states in order to install ``sys-net`` without checking ``Create default system qubes (sys-net, sys-firewall, default DispVM)`` at the first install. Maybe we should come with an additional PR which would not attempt adding a known-buggy wifi adapters such as this.

And these two issues:
- the ``Fn`` key stops working in dom0, domU as soon as I attach the USB controller to a domU (typically sys-usb or sys-net); By "the ``Fn`` key stops working, I mean that the touch bar display (connected over a USB interface under the hood) won't toggle between special (brightness, volume, ...) keys and function-keys (F1..12).
- For the touchbar (don't mix with the touchpad) to work, one needs to run the following commands or follow this procedure if wish doing this manually https://www.qubes-os.org/doc/usb-qubes/#enable-a-usb-keyboard-for-login
  ```
  sudo qubesctl state.sls qvm.usb-keyboard
  ```

----
Child PR: https://github.com/QubesOS/qubes-installer-qubes-os/pull/36
Child PR: https://github.com/QubesOS/qubes-core-admin-linux/pull/57
Related issue: https://github.com/QubesOS/qubes-issues/issues/3784

### CODE REVIEW

**Comment by marmarek** [comment]
How is it different from the upstream version in Linux>=5.3?

>     * so the system won't freeze during `qubes-vm@sys-net` installation/start-up

You can add `qubes.skip_autostart` to the kernel command line to prevent starting any VM automatically - it should also apply to the final step of initial setup. And you can do that at the end of installation, before reboot.

>     * the `Fn` key stops working in dom0, domU as soon as `qube-vm@sys-net` is started; (or qube-vm@sys-usb, or any qube? I haven't checked this deeper)

Rather sys-usb. But if the device appears and works in sys-usb, it may be possible to enable it back: https://www.qubes-os.org/doc/usb-qubes/#enable-a-usb-keyboard-for-login

**Comment by marmarek** [comment]
> How is it different from the upstream version in Linux>=5.3?

Or rather: why is it different? Do you know whether there are plans to sync them up, or are there some fundamental issues preventing this version of the driver being included upstream?

**Comment by arno01** [comment]
> > ```
> > * so the system won't freeze during `qubes-vm@sys-net` installation/start-up
> > ```
> 
> You can add `qubes.skip_autostart` to the kernel command line to prevent starting any VM automatically - it should also apply to the final step of initial setup. And you can do that at the end of installation, before reboot.

This is a good point and is almost what I usually do when I am hooking a USB keyboard since it is allowing me switching between the Anaconda installer (X11) and the console (e.g. using ``Ctrl+Alt+F3``) where I could either add ``module_blacklist=xen_pciback`` or run  ``systemctl mask qubes-vm@sys-net`` (in chroot) or as you have suggested, add ``qubes.skip_autostart`` commandline option.

The real issue with the Macbook keyboard is that it still won't let me use ``Ctrl+Alt+F1..12`` key combinations even while in the Anaconda installer (X11). This is why this forces me to boot using Grub2 CLI manually or hook the USB keyboard [to a USB-C port].
Both things are a huge PITA for anyone installing Qubes OS on his Macbook.
Therefore, I think that we should blacklist the known-to-fail Broadcom adapters from attaching to the ``qubes-vm@sys-net`` upon first boot wizard setup and only then we can probably try figuring out how to make the ``Ctrl+Alt+F1..12 in X11 & Ctrl-X, F10 in Grub2`` key combinations working.
The blacklisting can probably be done in the https://github.com/QubesOS/qubes-mgmt-salt-base/blob/2325514e53837d1d3fff6c6088f410e0be9252f4/_grains/pci_devs.py#L30 e.g. ``14e4:43ba`` - WDYT?

```
$ lspci -s 03:00.00 -mm -nn
03:00.0 "Network controller [0280]" "Broadcom Inc. and subsidiaries [14e4]" "BCM43602 802.11ac Wireless LAN SoC [43ba]" -r02 "Apple Inc. [106b]" "Device [0173]"
```

> > ```
> > * the `Fn` key stops working in dom0, domU as soon as `qube-vm@sys-net` is started; (or qube-vm@sys-usb, or any qube? I haven't checked this deeper)
> > ```
> 
> Rather sys-usb. But if the device appears and works in sys-usb, it may be possible to enable it back: https://www.qubes-os.org/doc/usb-qubes/#enable-a-usb-keyboard-for-login

Just to clarify, by ``the `Fn` key stops working`` I mean that the touch bar (connected over a usb interface under the hood) display won't switch between special (brightness, volume, ...) and function-keys (F1..12).

I don't have the ``sys-usb`` as I've picked ``[x] Use sys-net qube for both networking and USB devices``, and then I ran ``sudo qubesctl top.enable qvm.usb-keyboard && sudo qubesctl state.highstate`` so it has removed ``rd.qubes.hide_all_usb`` and added ``sys-net dom0 allow,user=root`` to the ``/etc/qubes-rpc/policy/qubes.InputKeyboard`` file. (``/etc/qubes-rpc/policy/qubes.InputMouse`` was already set by the ``qvm.sys-usb`` salt state, since I have the ``qvm:sys-usb:name`` set to ``sys-net``)

I will reboot with ``qubes.skip_autostart`` commandline option and see whether Fn key is working in a moment.

**Comment by arno01** [comment]
To confirm: as soon as ``sys-net`` gets a control over the ``00:14.0`` (xhci_pci/hcd) USB controller, the touch bar display stops reacting to the Fn key for toggling between special (brightness, volume, ...) and function-keys (F1..12).

```
# qvm-pci | grep USB
dom0:00_14.0  USB controller: Intel Corporation 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller                                    sys-net (no-strict-reset=True)
...
```

I am wondering if this is something that can be easily fixed.

I've also noticed these messages when sys-net starts:

```
Jan 28 12:45:09 dom0 kernel: pciback 0000:00:14.0: cache line size of 256 is not supported
Jan 28 12:45:09 dom0 kernel: xen_pciback: 0000:00:14.0: cannot enable memory-write-invalidate (-22)
```

**Comment by arno01** [comment]
> > How is it different from the upstream version in Linux>=5.3?
> 
> Or rather: why is it different? Do you know whether there are plans to sync them up, or are there some fundamental issues preventing this version of the driver being included upstream?

Here are the differences;
https://gist.github.com/arno01/ba69b5956f6bb996fd7232bbe009f2de

I have no idea about the plans, there are plenty of links and "sub-links" if you drill down the initial upstream commit description https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=038b1a05eae6666b731920e46f47d8e2332e07ff ; there is even a [bug bounty project of $605 value](https://www.bountysource.com/issues/35422234-macbook8-1-12-inch-early-2015-keyboard-and-trackpad-don-t-work) but I don't have that model.

Without getting into the whole a lot of differences:
- keyboard/touchpad do not work on Macbook in Qubes R4.0 https://github.com/QubesOS/qubes-issues/issues/3784
- the upstream version doesn't work well on MacBookPro14,3, causing system instability, system freezes, cannot ``modprobe applespi``, ...
- touch**bar** patch isn't in the upstream linux as of today, so the only way to get it to work is to use roadrunner2's macbook12-spi-driver

**Comment by marmarek** [comment]
> The blacklisting can probably be done in the https://github.com/QubesOS/qubes-mgmt-salt-base/blob/2325514e53837d1d3fff6c6088f410e0be9252f4/_grains/pci_devs.py#L30 e.g. `14e4:43ba` - WDYT?
> 
> ```
> $ lspci -s 03:00.00 -mm -nn
> 03:00.0 "Network controller [0280]" "Broadcom Inc. and subsidiaries [14e4]" "BCM43602 802.11ac Wireless LAN SoC [43ba]" -r02 "Apple Inc. [106b]" "Device [0173]"
> ```

Yes, this sounds like a reasonable idea.

**Comment by marmarek** [comment]
I see you target stable-4.19 branch. Can you make this PR against master?

**Comment by marmarek** [comment]
> To confirm: as soon as `sys-net` gets a control over the `00:14.0` (xhci_pci/hcd) USB controller, the touch bar display stops reacting to the Fn key for toggling between special (brightness, volume, ...) and function-keys (F1..12).

I guess Fn still remains in dom0 and is not connected directly to the touchbar, rather use some OS driver to talk to it. And when those two gets separated, dom0 driver can no longer interact with touchbar usb device. That's just my wild guess.
The proper solution would probably involve some device-specific proxy to talk to touchbar in sys-usb/sys-net. Temporary hack could be leaving usb controller in dom0, or attaching touchbar to dom0 using qvm-usb (after adding support for connecting devices to dom0, which should be quite easy).

Does it affect only display, or actual key functions too? Can you set it to the more useful state at the system boot and will it stay this way?

**Comment by arno01** [comment]
> > To confirm: as soon as `sys-net` gets a control over the `00:14.0` (xhci_pci/hcd) USB controller, the touch bar display stops reacting to the Fn key for toggling between special (brightness, volume, ...) and function-keys (F1..12).
> 
> I guess Fn still remains in dom0 and is not connected directly to the touchbar, rather use some OS driver to talk to it. And when those two gets separated, dom0 driver can no longer interact with touchbar usb device. That's just my wild guess.

Yeah, this is what I am thinking as well.

> The proper solution would probably involve some device-specific proxy to talk to touchbar in sys-usb/sys-net. Temporary hack could be leaving usb controller in dom0, or attaching touchbar to dom0 using qvm-usb (after adding support for connecting devices to dom0, which should be quite easy).

I guess I could try monkeying with ``xl usbdev-attach`` to see if that works out. I've got 3 USB controllers, but it looks like everything runs through a single one ``00:14.0`` (USB wifi dongle, the external keyboard, the touchbar):

```
$ lspci  |grep USB
00:14.0 USB controller: Intel Corporation 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller (rev 31)
07:00.0 USB controller: Intel Corporation JHL6540 Thunderbolt 3 USB Controller (C step) [Alpine Ridge 4C 2016] (rev 02)
7d:00.0 USB controller: Intel Corporation JHL6540 Thunderbolt 3 USB Controller (C step) [Alpine Ridge 4C 2016] (rev 02)
```

> Does it affect only display, or actual key functions too?

Only the touchbar display, so the ``dom0 -/-> USB`` as we presume.
The other function I use Fn key for is the key combination ``Fn+Shift+Return`` (read ``Return`` is ``Enter`` on macs) it pastes the text in dom0 & domU as expected. That's the same as ``Shift+Insert`` on a non-mac keyboard.

> Can you set it to the more useful state at the system boot and will it stay this way?

Already do, passing ``fnmode=2`` to ``apple_ib_tb`` driver as in the other PR https://github.com/QubesOS/qubes-core-admin-linux/pull/57/files#diff-3f411eb6b85ac32e6d47bc36f778add6R1 which I need to re-do.

**Comment by arno01** [comment]
I think I know why I cannot switch between X11 and the VT using the ``Ctrl+Alt+Fn`` sequence...
lightdm has ``-novtswitch`` hardcoded when it starts the X11 :-/

```
root        2328       1  0 14:20 ?        00:00:00 /usr/sbin/lightdm
root        2357    2328  5 14:20 tty1     00:00:12 /usr/bin/X -core -noreset :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt1 -novtswitch
``` 

There is a patch https://lists.freedesktop.org/archives/lightdm/2015-May/000796.html for lightdm to allow VT switch using ``xserver-allow-vt-switch=true`` flag in ``lightdm.conf``.

**Comment by marmarek** [comment]
> lightdm has `-novtswitch` hardcoded when it starts the X11 :-/

It doesn't block switching. It avoids X server automatically switching to its own tty on startup.

**Comment by arno01** [comment]
> > The proper solution would probably involve some device-specific proxy to talk to touchbar in sys-usb/sys-net. Temporary hack could be leaving usb controller in dom0, or attaching touchbar to dom0 using qvm-usb (after adding support for connecting devices to dom0, which should be quite easy).
> 
> I guess I could try monkeying with `xl usbdev-attach` to see if that works out. I've got 3 USB controllers, but it looks like everything runs through a single one `00:14.0` (USB wifi dongle, the external keyboard, the touchbar):

I can't seem to attach my USB WiFi dongle:

```
[arno@dom0 ~]$ lsusb | grep TP
Bus 001 Device 003: ID 2357:010c TP-Link TL-WN722N v2
[arno@dom0 ~]$ sudo xl usbdev-attach sys-net hostbus=1 hostaddr=3
libxl: error: libxl_qmp.c:1836:qmp_ev_parse_error_messages: Domain 9:'usb-host' is not a valid device model name
libxl: error: libxl_device.c:1414:device_addrm_aocomplete: unable to add device
libxl_device_usbdev_add failed.
```

> So, I guess, it is working, except that `xev` running in domU doesn't show anything when I press the `Fn` key alone. Not sure if it should.

I am now running with the ``00:14.0`` (my USB 3.0 xHCI controller) detached from any qubes VM, so the F1..12 touchbar is fully functioning. I've tried running ``xev`` while pressing Ctrl+Alt+F3 (and other keys), xev reports that it receives the ``XF86Switch_VT_3``, except that it does not switch me to the VT_3 (or any other I've tried)... :-/

```
[arno@dom0 ~]$ xev
... Pressing Ctrl+Alt+F3 ...

KeymapNotify event, serial 30, synthetic NO, window 0x0,
    keys:  52  0   4294967168 0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeymapNotify event, serial 30, synthetic NO, window 0x0,
    keys:  52  0   4294967168 0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeyRelease event, serial 30, synthetic NO, window 0x5000001,
    root 0x534, subw 0x0, time 4521446, (490,83), root:(1841,919),
    state 0x0, keycode 23 (keysym 0xff09, Tab), same_screen YES,
    XLookupString gives 1 bytes: (09) "	"
    XFilterEvent returns: False

KeyPress event, serial 30, synthetic NO, window 0x5000001,
    root 0x534, subw 0x0, time 4523096, (490,83), root:(1841,919),
    state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 30, synthetic NO, window 0x5000001,
    root 0x534, subw 0x0, time 4523532, (490,83), root:(1841,919),
    state 0x4, keycode 133 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

MappingNotify event, serial 30, synthetic NO, window 0x0,
    request MappingKeyboard, first_keycode 8, count 248

KeyRelease event, serial 31, synthetic NO, window 0x5000001,
    root 0x534, subw 0x0, time 4524277, (490,83), root:(1841,919),
    state 0xc, keycode 69 (keysym 0x1008fe03, XF86Switch_VT_3), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

MappingNotify event, serial 31, synthetic NO, window 0x0,
    request MappingKeyboard, first_keycode 8, count 248

KeyRelease event, serial 31, synthetic NO, window 0x5000001,
    root 0x534, subw 0x0, time 4527283, (490,83), root:(1841,919),
    state 0xc, keycode 133 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x5000001,
    root 0x534, subw 0x0, time 4527321, (490,83), root:(1841,919),
    state 0x4, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

ClientMessage event, serial 32, synthetic YES, window 0x5000001,
    message_type 0x131 (WM_PROTOCOLS), format 32, message 0x12f (WM_DELETE_WINDOW)
```

**Pull request merged**
