### PR TITLE
Remove checked in symlinks to fc20 from pkgs/

### PR DESCRIPTION
**Pull request by jgriffiths**
Looks like these were checked in in error, they break the build when DIST_DOM0=fc23 is set.

Note that related change for 3.19 at https://github.com/QubesOS/qubes-linux-kernel/commit/e2aa9596eb029a6f77dc35ddfe49a662d66808ac should also remove pkgs/.gitignore but doesn't currently.

### CODE REVIEW

**Comment by marmarek** [comment]
Those symlinks are to use the same kernel-devel for every VM - in case of someone want to build kernel module in the VM. In fact my local clone have all three (fc21, fc22, fc23) pointing at fc20.
Anyway this is probably good idea to not have them in the repository. Otherwise every dom0 version would require separate branch (in practice this is the case, but in theory don't need to be).

**Comment by jgriffiths** [comment]
>Anyway this is probably good idea to not have them in the repository. Otherwise every dom0 version would require separate branch (in practice this is the case, but in theory don't need to be).

Absolutely.

**Comment by marmarek** [comment]
I think you wanted to base this (and the other one linux-kernel PR) on `stable-4.1` branch, not `stable-3.18`. If you don't want to create new PRs, I can simply cherry-pick those two commits and close PRs manually.

**Comment by jgriffiths** [comment]
Hi @marmarek if you could cherry pick these and close that would be great, thanks!

**Pull request closed without merging**
