### PR TITLE
build wireguard module

### PR DESCRIPTION
**Pull request by xaki23**
this adds wireguard as a module, built the same way as u2mfn ("out of tree kbuild")

### CODE REVIEW

**Comment by fepitre** [comment]
Please rebase first on the master branch to avoid the 'Merge http://github.com/QubesOS/qubes-linux-kernel'

**Comment by marmarek** [comment]
It looks they also publish signatures of tarballs - see https://git.zx2c4.com/WireGuard/ (sig link). It would be good to use that in addition/instead of static hash.

**Comment by xaki23** [comment]
two tiny "more invasive" changes in this ... 
a) changed glob pattern when importing the kernel gpg key (to avoid conflict with the wireguard key)
b) delete kernel sig file on clean-sources (instead of just the source tarball)

(and sorry for the additional recommits/forcepushes, but i dont really know how to properly check a commit "offline" while a PR is already open. if you prefer a fresh PR whenever i change my mind on my own repo, just holler...)

**Comment by marmarek** [comment]
force-push to already open PR is fine. Just remember to leave also a comment, as github doesn't send notifications in that case.

**Pull request merged**
