### PR TITLE
Update to 4.14.18

### PR DESCRIPTION
**Pull request by HW42**
Fixes QubesOS/qubes-issues#3507

### CODE REVIEW

**Comment by rtiangha** [comment]
If possible, it might be better to wait until 4.14.18 to come out before pushing out a new Qubes version. It should be out soon, and it includes the next round of Spectre fixes including Specture v1 mitigations and initial IBRS/IPBP support, all scheduled to be merged into Kernel 4.16 so this next release should all be caught up with the latest mitigations.

**Comment by HW42** [comment]
FWIW: AFAIK IBRS/IPBP can only be used after support has been added to Xen. And so far the SP2 patches are (AFAICS) only in master.

PS: Pushed the missing signed tag.

**Comment by rtiangha** [comment]
4.14.18 is now out.

**Comment by marmarek** [comment]
@HW42 do you want to bump version to .18, or should I merge this now?

**Comment by HW42** [comment]
Updated to and tested 4.14.18

**Pull request merged**
